# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T12:06:58+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, RootModel


class Error(BaseModel):
    code: int
    message: str


class Pet(BaseModel):
    id: int
    name: str
    tag: Optional[str] = None


class Pets(RootModel[List[Pet]]):
    root: List[Pet]
